name: Deploy prod site on push

on: 
  push:
    branches: 
      - main
      
jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ExpensesTracker/ClientApp

    env:
      SERVER: www07.servertown.ch

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build
    
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ env.SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ./kostenmanager.tomasi-developing.ch
        dangerous-clean-slate: true
